#!/bin/bash
set -ex

OS=$(uname -s | tr A-Z a-z)

case $OS in
  linux)
    source /etc/os-release
    case $ID in
      debian|ubuntu|mint
        updt="$(apt list --upgradable | wc -l)"
        ;;
      
      fedora|rhel|centos
        updt="$(dnf check-update | wc -l)"
        ;;
      arch
        updt="$(pacman -Qu | wc -l)"

printf "%s " "$updt"
